- platform: simple_thermostat
  name: "Kaminzimmer"
  unique_id: "kaminzimmer_thermostat"

  # Sensor IDs (automatically constructs full entity IDs)
  temperature_sensor_id: "0x983268fffe9878e4"

  # TRV configuration with optional names
  trv_ids:
    - id: "0x08b95ffffe5184ce"
      name: "Hauptventil"  # Optional: friendly name for sensors

  # Preset temperatures (°C) - adjust to your preference
  away_temp: 18.0
  present_temp: 21.0
  cosy_temp: 23.0

  # Control thresholds
  binary_threshold: 0.5
  hysteresis: 0.3

  # Remote temperature sync
  sync_remote_temp: true

  # Initial preset
  initial_preset: present
